services:
  - type: web
    name: waec-backend
    env: node
    buildCommand: chmod +x render-build.sh && ./render-build.sh
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        fromSecret: MONGODB_URI
      - key: JWT_SECRET
        fromSecret: JWT_SECRET
      - key: PORT
        value: 10000